//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersPrject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string orderNumber { get; set; }
        public string productName { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
